version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: elasticsearch
    restart: always
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - elk

  logstash:
    image: logstash:8.5.0
    container_name: logstash
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    image: kibana:8.5.0
    container_name: kibana
    restart: always       
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch  
    networks:
      - elk
volumes:
  elastic_data: {}

networks:
  elk: